name: Build and Test
on:
  pull_request:
    branches:
      - main
jobs:
  build-test:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v2

      - name: Setup Dependencies Cache
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'yarn'

      - name: Install Dependencies
        run: yarn install

      - name: Build
        run: yarn build